### ISSUE TITLE
Глава 4.7 Стоит добавить вариант для длинных типов

### ISSUE THREAD

**Issue by gimntut** [alexey-goloburdin/typed-python-book#1]
`self._some_dict: dict[str, int] = {}` - читается достаточно легко
`self._some_dict: dict[Coordinates, Celsius] = {}` - Логика теряется на фоне описания типов
`self._some_dict = {}  # type: dict[Coordinates, Celsius] ` - логика отдельно, ~~мухи~~ описание отдельно

Ещё такой подход помогает в циклах:
Нельзя написать `for index:int, value:int in enumerate(data):`
Но можно написать так:
``` python
data = load.jsons(dump)
for index, value in enumerate(data):  # type: int, int
  ...
```

**Comment by alexey-goloburdin** [comment]
@gimntut есть какая-то информация о том, насколько рекомендуется/не рекомендуется таким пользоваться? Насколько я вижу картину — [PEP 484](https://peps.python.org/pep-0484/) ввел аннотации для функций, а аннотации для переменных писались в комментариях. Потом появился [PEP 526](https://peps.python.org/pep-0526/), который как раз обосновывает, почему нужен синтаксис для аннотирования обычных переменных и почему синтаксис в комментариях не лучший выбор. Там приводятся обоснования по этому поводу, они здравые.

Насколько я понял такой способ указания типов не является рекомендуемым сейчас, хотя и работает. С поинтом про улучшение читаемости для длинных типов я возможно согласен, хотя можно создать alias типа для такого случая и разделить сложное описание типа и использование этого типа.

**Comment by gimntut** [comment]
К сожалению, кроме ссылки на [примеры mypy](http://mypy-lang.org/examples.html) не могу ничего предоставить в защиту своего мнения. В первом же примере приводится тип через комментарии. Но, возможно, примеры устарели.

**Comment by gimntut** [comment]
Будет плохо, если в книгу попадут неправильные советы. Пока нет времени глубоко погружаться в этот вопрос. Поэтому пока закрою эту задачу, 

Могу рассказать откуда и почему я взял приём с типами в комментариях. 
У меня была проблема с циклическими импортами из-за внедрения типизации в свой проект. Проект делался на версии python 3.6. Перейти на свежую версию сложно, т.к. на проде вместо докера используется legacy в виде venv. Поэтому воспользовался советом https://mypy.readthedocs.io/en/latest/runtime_troubles.html#class-name-forward-references

Возможно я просто пропустил такую главу (искал по слову TYPE_CHECKING), но в книге, вообще не упоминается, что внедрение типов может приводить к проблемам. При этом в документации mypy про это есть есть целых два раздела:
* https://mypy.readthedocs.io/en/stable/common_issues.html
* https://mypy.readthedocs.io/en/stable/runtime_troubles.html

Возможно, стоило бы добавить в конец книги главу о проблемах и их решениях.
